import type { Phase } from "./types";

// Up design system color tokens
export const UP = {
  sunset: "#FF7A64",       // primary action
  pink: "#FF8BB5",         // accent
  green: "#00BC83",        // credit / success
  blue: "#3FA8F4",         // sometimes-blue
  sunrise: "#FFF06B",      // caution / highlight
  midnight: "#242430",
  midnightDark: "#1A1A22",
  textPrimary: "rgba(255,255,255,0.98)",
  textSecondary: "rgba(255,255,255,0.60)",
  textTertiary: "rgba(255,255,255,0.47)",
  cardSurface: "rgba(255,255,255,0.05)",
  borderSecondary: "rgba(255,255,255,0.10)",
  borderPrimary: "rgba(255,255,255,0.20)",
};

export const phases: Phase[] = [
  {
    id: "mvp",
    label: "MVP",
    sublabel: "Shipping now",
    color: UP.sunset,
    dotColor: UP.sunset,
    features: [
      {
        id: "parental-controls",
        title: "Parental Controls",
        description: "Full visibility and control for parents. Set limits, approve transactions, and freeze accounts instantly.",
        detail: "Parents get a dedicated dashboard inside the existing Up app. Approve or deny spending, set daily limits per category, receive real-time push notifications for every transaction, and freeze the card with one tap. Complete audit trail of all activity.",
        icon: "🛡️",
        color: UP.sunset,
        tag: "Core",
      },
      {
        id: "legalities",
        title: "Legal & Compliance",
        description: "Age-verified accounts for under-18s with full AML/KYC compliance, backed by Up's existing banking licence.",
        detail: "Custodial account structure where the parent/guardian is the account holder. Under-18 accounts operate under parental supervision. Full AUSTRAC compliance, AML/KYC checks on parent accounts, and AFSL-compliant product disclosure. Terms designed for minors.",
        icon: "📋",
        color: UP.sunset,
        tag: "Core",
      },
      {
        id: "spending-account",
        title: "Kids Spending Account",
        description: "A real debit account for everyday spending with an Up card in their name.",
        detail: "A fully functional spending account with a physical Up debit card (custom kids design). Works anywhere Visa is accepted. Real-time balance visible to both parent and child. Spending notifications sent to parent instantly. No overdraft possible.",
        icon: "💳",
        color: UP.sunset,
        tag: "Core",
      },
      {
        id: "savings-buckets",
        title: "Savings Account + Savers",
        description: "Goal-based saving with Up's signature Savers. Kids create buckets for what they're working toward.",
        detail: "Up Savers adapted for kids. Create up to 10 buckets for specific goals — a new game, birthday gift, holiday spending money. Each bucket shows progress, target date, and amount needed per week. Parents can contribute directly to any bucket.",
        icon: "🪣",
        color: UP.sunset,
        tag: "Core",
      },
      {
        id: "parent-tab",
        title: "Parent Tab in Up App",
        description: "A dedicated Parents section inside the existing Up app — no second app required.",
        detail: "Integrated as a new tab in the current Up app. Parents see all linked child accounts, recent activity, pending approvals, and quick actions. Seamlessly switches between your own Up account and the kids view. Family overview dashboard.",
        icon: "👨‍👩‍👧",
        color: UP.sunset,
        tag: "Core",
      },
      {
        id: "child-login",
        title: "Child Login Space",
        description: "A kid-first interface inside the Up app — bright, simple, and age-appropriate.",
        detail: "Kids log in with a simplified PIN or Face ID on a parent-approved device. They see a bright, simplified view of their balance, recent transactions, and savings goals. No access to account settings, card details, or transfer features without parent approval.",
        icon: "🔑",
        color: UP.sunset,
        tag: "Core",
      },
    ],
  },
  {
    id: "phase2",
    label: "Phase 2",
    sublabel: "6–12 months",
    color: UP.pink,
    dotColor: UP.pink,
    features: [
      {
        id: "avatar-xp",
        title: "Avatar & XP Space",
        description: "Kids earn XP by hitting savings goals and unlock items to decorate their personal Up space.",
        detail: "A persistent avatar and virtual room that grows with the child. Earn XP for hitting savings targets, keeping a streak, and completing financial challenges. Unlock furniture, accessories, and avatar outfits. Seasonal and limited-edition items create excitement and reward consistency.",
        icon: "🎮",
        color: UP.pink,
        tag: "Engagement",
      },
      {
        id: "education-tab",
        title: "Education Tab",
        description: "Age-staged financial literacy content. The right lesson at the right age — from coins to compound interest.",
        detail: "Content tailored to 5 age brackets:\n• 6–7 yrs: Value of coins & notes, counting change\n• 7–9 yrs: Ways to pay, lending & borrowing basics\n• 9–11 yrs: Foreign currency, influences on spending\n• 11–14 yrs: Budgeting, financial paperwork, bank accounts\n• 14–16 yrs: Income, tax, planning for independence\n\nBite-sized lessons, quizzes, and real-world challenges. Completion earns XP.",
        icon: "📚",
        color: UP.pink,
        tag: "Education",
      },
      {
        id: "parent-learning",
        title: "Parents Learning Hub",
        description: "Practical guides for parents on how to talk to kids about money — at every age.",
        detail: "Evidence-based articles and conversation starters for parents. 'How do I explain debt to a 9-year-old?' 'When should my teen get a credit card?' Short video guides, age-specific scripts, and expert-backed frameworks. Pairs directly with the Education Tab so parents know what their child is learning.",
        icon: "🧑‍🏫",
        color: UP.pink,
        tag: "Education",
      },
      {
        id: "chores",
        title: "Chores & Earn",
        description: "Parents post chores with a dollar value. Kids complete, photo-verify, and earn — with parent approval.",
        detail: "Parents create a chore with a title, description, and payment amount. The kid marks it done and submits a photo as proof. Parent approves in one tap and the money moves instantly to the kid's account. Recurring chores auto-post weekly. Kids see their total earned this month.",
        icon: "🧹",
        color: UP.pink,
        tag: "Earn",
      },
    ],
  },
  {
    id: "phase3",
    label: "Phase 3",
    sublabel: "12–24 months",
    color: UP.green,
    dotColor: UP.green,
    features: [
      {
        id: "loan-me-later",
        title: "Loan Me Later",
        description: "Parents advance cash for a big spend. Kids repay over time — with real payoff projections.",
        detail: "'This bike costs $280. Mum will lend you $200 and you'll pay back $28 a week for 10 weeks.' Parents set repayment terms, kids accept the plan. Automatic weekly deductions from pocket money or earnings. Both sides see the outstanding balance and payment history. Teaches real credit mechanics without real risk.",
        icon: "🤝",
        color: UP.green,
        tag: "Credit",
      },
      {
        id: "job-quiz",
        title: "First Job Calculator",
        description: "When kids get their first job, a quiz turns their wage into tangible saving milestones.",
        detail: "A one-time onboarding quiz: job type, hours per week, hourly rate. The app calculates take-home pay after tax and projects savings over time. 'Saving $50 a week = your first laptop in 6 months.' Future goals shown as '70 hours of work' or '4 weeks of shifts'. Connects real income to savings goals.",
        icon: "💼",
        color: UP.green,
        tag: "Work",
      },
      {
        id: "family-goals",
        title: "Family Savings Goals",
        description: "The whole family chips in toward a shared goal — holiday, trampoline, family night out.",
        detail: "Parents create a family goal with a target amount and date. Every family member can contribute from their own account. Kids see exactly how much they've contributed and how close the family is to the goal. Celebration screen when the goal is hit. Teaches collaborative financial planning.",
        icon: "🏆",
        color: UP.green,
        tag: "Family",
      },
      {
        id: "insights",
        title: "Kid Spending Insights",
        description: "Monthly wrapped-style insights for kids — where did my money go this month?",
        detail: "At month's end, a fun animated summary: biggest spend category, longest saving streak, total earned from chores, and a comparison to last month. Shareable card for kids to show parents. Yearly 'Money Story' wraps up the financial year. Modelled on Up's existing Insights but redesigned for kids.",
        icon: "📊",
        color: UP.green,
        tag: "Insights",
      },
    ],
  },
  {
    id: "explore",
    label: "Explore",
    sublabel: "Future ideas",
    color: UP.blue,
    dotColor: UP.blue,
    features: [
      {
        id: "investment-intro",
        title: "Investing 101",
        description: "A simulated investing experience that teaches shares, ETFs, and dividends before going real.",
        detail: "Start with a virtual $1,000 portfolio and invest in real ASX-listed companies and ETFs. Prices are real, but money is virtual. Once 18, the simulated portfolio converts to a real brokerage account. Teaches risk, diversification, and long-term thinking.",
        icon: "📈",
        color: UP.blue,
        tag: "Invest",
      },
      {
        id: "peer-gifting",
        title: "Birthday Money",
        description: "Friends and family send birthday money directly to a kid's Up account or a specific bucket.",
        detail: "Parents share a unique gift link. Grandparents, friends, and relatives tap the link, choose an amount and a note, and pay via any payment method. Money lands in the child's savings account or a specific bucket they've picked. No more cash in envelopes.",
        icon: "🎁",
        color: UP.blue,
        tag: "Social",
      },
      {
        id: "teen-card",
        title: "Teen Card (14+)",
        description: "More autonomy for teens — higher limits, online payments, and a sleek dark-mode card design.",
        detail: "At 14, kids unlock the Teen tier. Higher daily limit, online payment capability, Apple Pay and Google Pay support. A new card design that doesn't scream 'kids account'. Still parent-linked but with more independence. Different notification preferences — daily summary instead of every transaction.",
        icon: "🪪",
        color: UP.blue,
        tag: "Teen",
      },
    ],
  },
];
